### ISSUE TITLE
Prompt for adding maskmeister.keywordsFilePath to user settings

### ISSUE THREAD

**Issue by AndBlo** [henrikroschmann/MaskMeister#1]
The overall initial experience would benefit from the extension prompting the user where the keywords-file should be, when using any command if this has not yet been specified in user settings.

The keywords-file should also be automatically created

**Comment by henrikroschmann** [comment]
If the location is missing in the settings.json the user is notified 
![image](https://github.com/henrikroschmann/MaskMeister/assets/17333/38064548-373c-4839-bc3d-283f25611c61)

Now you can configure the path of the keywords in the ui
![image](https://github.com/henrikroschmann/MaskMeister/assets/17333/fc9ea4be-ecd2-461f-8aa5-cdcd53d603ab)

when creating a new keywords file a default value is added.
