### ISSUE TITLE
Prefix the commands for easier navigation 

### ISSUE THREAD

**Issue by AndBlo** [henrikroschmann/MaskMeister#2]
The commands should be prefixed with **MaskMester: [command]**. This would make it easier to get an overview of available commands when using commands shortcut (Ctrl+Shift+P on windows)

**Comment by henrikroschmann** [comment]
![image](https://github.com/henrikroschmann/MaskMeister/assets/17333/cfb0df4c-98ef-4676-a50a-4429e15e43b0)

Fixed in latest
